replicaCount: 2

image:
  repository: ghcr.io/example/swifty-server
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 75

redis:
  host: redis-master.default.svc.cluster.local
  port: 6379
  db: 0
  passwordSecret: ""

rateLimiting:
  httpRequestsPerMinute: 600
  httpWindowSeconds: 60
  httpMaxConcurrentRequests: 200
  httpThrottleTimeoutSeconds: 0.25
  websocketMessageRate: 900
  websocketMessageWindowSeconds: 60
  websocketMaxConnections: 4000
  trustForwardedHeaders: true

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  hosts:
    - host: swifty.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: swifty-server-tls
      hosts:
        - swifty.example.com

env:
  ACCESS_TOKEN_EXPIRE_MINUTES: "15"
  REFRESH_TOKEN_EXPIRE_MINUTES: "1440"
  OTEL_EXPORTER_OTLP_ENDPOINT: ""
  OTEL_SERVICE_NAME: swifty-server

additionalEnv: []

extraVolumeMounts: []
extraVolumes: []

nodeSelector: {}
tolerations: []
affinity: {}
