version: "3.9"

services:
  app:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    image: swifty-server:latest
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    expose:
      - "8000"

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data

  proxy:
    image: nginx:1.25-alpine
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/tls:ro
    environment:
      - NGINX_RESOLVER=127.0.0.11

volumes:
  redis-data:
