apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "swifty-server.fullname" . }}-env
  labels:
    {{- include "swifty-server.labels" . | nindent 4 }}
data:
  REDIS_HOST: "{{ .Values.redis.host }}"
  REDIS_PORT: "{{ .Values.redis.port }}"
  REDIS_DB: "{{ .Values.redis.db }}"
  HTTP_RATE_LIMIT_PER_MINUTE: "{{ .Values.rateLimiting.httpRequestsPerMinute }}"
  HTTP_RATE_LIMIT_WINDOW_SECONDS: "{{ .Values.rateLimiting.httpWindowSeconds }}"
  HTTP_MAX_CONCURRENT_REQUESTS: "{{ .Values.rateLimiting.httpMaxConcurrentRequests }}"
  HTTP_THROTTLE_TIMEOUT_SECONDS: "{{ .Values.rateLimiting.httpThrottleTimeoutSeconds }}"
  HTTP_TRUST_FORWARDED_HEADERS: "{{ ternary "1" "0" .Values.rateLimiting.trustForwardedHeaders }}"
  WEBSOCKET_MESSAGE_RATE: "{{ .Values.rateLimiting.websocketMessageRate }}"
  WEBSOCKET_MESSAGE_WINDOW_SECONDS: "{{ .Values.rateLimiting.websocketMessageWindowSeconds }}"
  WEBSOCKET_MAX_CONNECTIONS: "{{ .Values.rateLimiting.websocketMaxConnections }}"
  OTEL_SERVICE_NAME: "{{ .Values.env.OTEL_SERVICE_NAME }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.env.OTEL_EXPORTER_OTLP_ENDPOINT }}"
  ACCESS_TOKEN_EXPIRE_MINUTES: "{{ .Values.env.ACCESS_TOKEN_EXPIRE_MINUTES }}"
  REFRESH_TOKEN_EXPIRE_MINUTES: "{{ .Values.env.REFRESH_TOKEN_EXPIRE_MINUTES }}"
